@DstServerQuery.Web_HostAddress = http://127.0.0.1:3000
@ApiVersion = 2

//获取饥荒版本
POST {{DstServerQuery.Web_HostAddress}}/api/v{{ApiVersion}}/server/Version

###

//请求列表
POST {{DstServerQuery.Web_HostAddress}}/api/v{{ApiVersion}}/server/list
Content-Type: application/json

{
  
}
###