@Ilyfairy.DstServerQuery.Web_HostAddress = http://127.0.0.1:3000
@version:apiVersion = 2

//获取饥荒版本
POST {{Ilyfairy.DstServerQuery.Web_HostAddress}}/api/v{{version:apiVersion}}/server/Version

###

//请求列表
POST {{Ilyfairy.DstServerQuery.Web_HostAddress}}/api/v{{version:apiVersion}}/server/list
Content-Type: application/json

{
  
}
###